audio:
  sample_rate: 22050
  n_mels: 80
  hop_size: 256
  win_size: 1024

training:
  batch_size: 32
  epochs: 100
  lr: 1e-4

paths:
  g2p_file: . # /g2p.txt
  metadata_dir: ./data # /metadata.txt
  output_dir: ./outputs